name: Metrics
on:
    push:
        branches:
            - main

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                output_action: pull-request
                committer_branch: main
                committer_message: update ${filename}
