name: Metrics
on:
    schedule:
        - cron: '30 1 * * *'

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                token: ${{ secrets.ACCESS_TOKEN }}
                output_action: pull-request
                committer_branch: main
                committer_message: update ${filename}
